### ISSUE TITLE
Add sub-user0018 to sct-testing-large

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#108]
See email _Date: Mon, Jul 19, 2021 at 4:44 PM Subject: Sample SC data from our Prisma scanner_

I have pushed the data on `sct-testing-large` branch `af/add_sub-user0018`

Here is the log:

<details>

```
[21/07/21 3:37:39] (base) alex@NeuroPoly-MacBook-Pro sct-testing-large % git annex sync --content origin    
commit 
On branch af/add_sub-user0018
nothing to commit, working tree clean
ok
pull origin 
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.

ok
copy sub-user0018/anat/sub-user0018_T1w.nii.gz (to origin...) 
ok                                 
copy sub-user0018/anat/sub-user0018_T2star.nii.gz (to origin...) 
ok                                
copy sub-user0018/anat/sub-user0018_T2w.nii.gz (to origin...) 
ok                                
copy sub-user0018/anat/sub-user0018_acq-MToff_MTS.nii.gz (to origin...) 
ok                                
copy sub-user0018/anat/sub-user0018_acq-MTon_MTS.nii.gz (to origin...) 
ok                                
copy sub-user0018/anat/sub-user0018_acq-T1w_MTS.nii.gz (to origin...) 
ok                                
copy sub-user0018/anat/sub-user0018_acq-slab2_T1w.nii.gz (to origin...) 
ok                                 
copy sub-user0018/anat/sub-user0018_acq-slab2_T2w.nii.gz (to origin...) 
ok                                
copy sub-user0018/dwi/sub-user0018_dwi.nii.gz (to origin...) 
ok                                 
pull origin 
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.

ok
(recording state in git...)
push origin 
Enumerating objects: 32759, done.
Counting objects: 100% (32759/32759), done.
Delta compression using up to 12 threads
Compressing objects: 100% (21857/21857), done.
Writing objects: 100% (22758/22758), 2.55 MiB | 1.12 MiB/s, done.
Total 22758 (delta 18569), reused 0 (delta 0)
remote: Resolving deltas: 100% (18569/18569), completed with 9195 local objects.
To data.neuro.polymtl.ca:datasets/sct-testing-large
   34ad2946d4..199f9043bb  git-annex -> synced/git-annex
 * [new branch]            af/add_sub-user0018 -> synced/af/add_sub-user0018
ok
[21/07/21 3:38:34] (base) alex@NeuroPoly-MacBook-Pro sct-testing-large % git annex sync --content origin
commit 
On branch af/add_sub-user0018
nothing to commit, working tree clean
ok
pull origin 
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 29 (delta 20), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.
From data.neuro.polymtl.ca:datasets/sct-testing-large
   199f9043bb..801616dedc  git-annex  -> origin/git-annex
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

warning: There are too many unreachable loose objects; run 'git prune' to remove them.

ok
(merging origin/git-annex into git-annex...)
[21/07/21 3:38:54] (base) alex@NeuroPoly-MacBook-Pro sct-testing-large % git annex whereis sub-user0018/anat/*             
whereis sub-user0018/anat/sub-user0018_T1w.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_T2star.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_T2w.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_acq-MToff_MTS.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_acq-MTon_MTS.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_acq-T1w_MTS.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_acq-slab2_T1w.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
whereis sub-user0018/anat/sub-user0018_acq-slab2_T2w.nii.gz (1 copy) 
  	6c8420e2-ee60-4383-96ba-cb43ef3c5611 -- git@data.neuro.polymtl.ca:~/repositories/datasets/sct-testing-large.git [origin]
ok
```

</details>

**Comment by alexfoias** [comment]
@kousu @jcohenadad Could one of you please review the branch ? thanks

**Comment by alexfoias** [comment]
@kousu Could you please check the data ? thanks

**Comment by alexfoias** [comment]
@kousu Pinging you again

**Comment by kousu** [comment]
Just found this in my backlog!

First, my newlines mistake bit this again, so I fixed that up with:

```
dos2unix participants.tsv && git add participants.tsv && git commit --amend
```

I verified all the files are actually Niftis:

![Screenshot from 2021-11-26 17-56-27](https://user-images.githubusercontent.com/987487/143660132-02d9f8b6-2fdc-489f-b6b0-3fa9e2d6f70d.png)


Then I looked at the sidecars. They're all correctly JSONs, but I noticed the sidecar files all have this extraneous "Metadata" field:

```json
       "Metadata":
    {
      "added_by": "Alexandru Foias",
      "added_on": "2021-07-21",
      "contact": "Shiva Shahrampour",
      "URL": "email from 2021-07-19"
    }
```

[BIDS](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) makes it pretty clear to me that *everything* in a sidecar already is metadata, so nesting an extra "metadata" field doesn't make sense. Also, the "URL" field used in this case isn't a URL. If we're trying to do provenance tracking, why not just put it in the commit message? Commit messages are already timestamped and signed, so there's no need for `"added_on"` nor `"added_by"`. And I'd suggest, if the data came by email, that you include the full email addresses of yourself and Shiva and the subject line, to give an archivist more context to work with in case they want to dig into one of your inboxes in the future to verify the provenance.

So I think before we merge this that metadata field needs to get moved over to a git commit message, and fleshed out.

**Comment by kousu** [comment]
I've rebased and force-pushed the newline fix up to your branch @alexfoias. When you next work on it, make sure to do:

```
git fetch && git checkout af/add_sub-user0018 && git reset --hard af/add_sub-user0018
```

to be synced up.

**Comment by jcohenadad** [comment]
> BIDS makes it pretty clear to me that everything in a sidecar already is metadata, so nesting an extra "metadata" field doesn't make sense. Also, the "URL" field used in this case isn't a URL. If we're trying to do provenance tracking, why not just put it in the commit message? Commit messages are already timestamped and signed, so there's no need for "added_on" nor "added_by". And I'd suggest, if the data came by email, that you include the full email addresses of yourself and Shiva and the subject line, to give an archivist more context to work with in case they want to dig into one of your inboxes in the future to verify the provenance.
So I think before we merge this that metadata field needs to get moved over to a git commit message, and fleshed out.

I agree that some fields are redundant/meaningless and that the sidecar JSON might not be the best place for it-- however I still see the value in encoding that in the dataset (not only in the git commits-- eg if we move away from the dataset or zip it and share it with someone else, the info would be lost). Also, to get a quick overview of provenance/contact, maybe we can add columns in the participants.tsv file. We already do it for the spine-generic project and it prove extremely useful

**Comment by kousu** [comment]
> (not only in the git commits-- eg if we move away from the dataset or zip it and share it with someone else, the info would be lost). Also, to get a quick overview of provenance/contact, maybe we can add columns in the participants.tsv file. We already do it for the spine-generic project and it prove extremely useful

Then why bother with git?

It leaves the dataset denormalized, with inconsistently duplicated information spread between commits, .json and .tsv files. Provenance tracking is the one thing git is extremely good at, we should lean into it.

**Comment by jcohenadad** [comment]
> Then why bother with git?

because git provides a way to 'snapshot' a version of the dataset, which is important for reproducibility. Again, I think that an IRL discussion will clarify a few things in a more efficient way than back-to-back 200+ GH posts.
